version: "3.8"
services:
  app:
    image: us-central1-docker.pkg.dev/devops-465809/springboot-docker/hello-spring-boot:latest
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 